[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16" }

[dev]

  command = "npm run start"
  publish = "dist"
  environment = { NODE_VERSION = "16" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

